---
name: Manual Release Publish

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'The new version to create.'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease

env:
  HUSKY: '0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Package Manager Setup
        run: |
          pnpm set registry "https://registry.npmjs.org/"
          pnpm set //registry.npmjs.org/:_authToken $NPM_TOKEN
          pnpm whoami
      - name: Git Setup
        run: |
          git config --global user.email "bot@zutron.io"
          git config --global user.name "Zutron Release Bot"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Release
        run: |
          pnpm run build
          pnpm turbo-version -b ${{inputs.releaseVersion}}
          pnpm turbo-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
